__default__ :
    time : 6:00:00
    mem : 2G
    cpus-per-task : 1
    #output : "autosnake/{{rule}}-\\$JOB_ID.out"
    #err : "autosnake/{{rule}}-\\$JOB_ID.err"
    output : "autosnake/\\$JOB_ID.out"
    err : "autosnake/\\$JOB_ID.err"
    name : "job"
run_sim:
    mem : "4.5G"
admixfrog_input:
    mem : "2G"
run_admixfrog:
    mem : "2G"
admixfrog_frags:
    mem : 8G
