sim:
    __default__ :
        seq_len : 50_000_000
        rec : ["Physical_Pos"]
        rec_obs : ["Physical_Pos"]

coverage : 
    __default__ :
        coverage : [[1, 0]]
        ascertainment : ['hcneaden']

demography:
    __default__ :
        n_afr : 40
        n_asn : 0
        n_oce : 0
        t_gf_neaeur : 50000
        d_gf_neaeur : 25
        m_gf_neaeur_rev: 0
        m_gf_neaeur : 0.03
        t_gf_neaden : 120000
        d_gf_neaden : 25
        m_gf_neaden_rev: 0.01
        m_gf_neaden : 0.03
        t_gf_deneur : 0
        d_gf_deneur : 0
        m_gf_deneur_rev: 0.0
        m_gf_deneur : 0.0

admixfrog:
    __default__ :
        bin_size: 5000
        state_ids: ["AFR", "NEA"]
        cont_id : ['AFR']
rle:
    __default__ :
        run_penalty : .4

series:
    rle:
        R2 :
            run_penalty : [0.2]
        RTest5 :
            run_penalty : [0.1, 0.2, 0.4]
    demography:
        DHuman1: #scenario a1
            a_eur : [[45000, 45000, 30000,30000, 15000, 15000, 0, 0]]
            m_gf_neaeur : [0.03]
            m_gf_neaeur_rev : [0.00]
            t_gf_neaeur : [50000]
        DHumanDenAdmix1: 
            a_eur : [[45000, 45000, 30000,30000, 15000, 15000, 0, 0]]
            m_gf_neaeur : [0.03]
            t_gf_neaeur : [50000]
            m_gf_deneur : [0.005]
            t_gf_deneur : [50000]
        DHuman_prop1: 
            a_eur : [[45000, 45000, 30000,30000, 15000, 15000, 0, 0]]
            m_gf_neaeur : [0, 0.002, 0.01, 0.03 ]
            t_gf_neaeur : [50000]
            m_gf_deneur : [0.000]
            t_gf_deneur : [50000]
        DDentime1: #scenario a2
            a_den : [[110000, 110000, 100000, 100000, 70000, 70000]]
            m_gf_neaden : [0.05]
            m_gf_neaden_rev : [0.0, 0.01, 0.05]
            t_gf_neaden : [120000]
            d_gf_neaden : [25, 500, 10000]
        DDen1: #scenario a2
            a_den : [[110000, 110000, 100000, 100000, 70000, 70000, 50000, 50000]]
            m_gf_neaden : [0.05]
            m_gf_neaden_rev : [0.0]
            t_gf_neaden : [120000]
    admixfrog:
        A3binsMH: #a1
            bin_size : [2000, 5000, 10000]
            state_ids: [["AFR", "NEA"]]
        A1binMH: #a1
            bin_size : [5000]
            state_ids: [["AFR", "NEA"]]
        A1bin2MH: #a1
            bin_size : [5000]
            state_ids: [["AFR", "NEA"], ['AFR', 'NEA', 'DEN']]
        A1binDEN:
            bin_size : [5000]
            state_ids: [["NEA", "DEN"]]
        A1binARC:
            bin_size : [5000]
            state_ids: [["NEA", "ARC"]]
        A3binsDEN:
            bin_size : [2000, 5000, 10000]
            state_ids: [["NEA", "DEN"]]
    sim:
        SBasic:
            seq_len : [50_000_000 ]
            rec : ['Physical_Pos']
    coverage : 
        C1hcneaden:
            coverage : [[[2, 0]]]
            ascertainment: ['hcneaden']
            rec_obs : ['Physical_Pos']
        C1archaicadmixture:
            coverage : [[[2, 0]]]
            ascertainment: ['archaicadmixture']
            rec_obs : ['Physical_Pos']
        CN4hcneaden:
            coverage : [[[0.03, 0]], [[0.1, 0]], [[0.5, 0]], [[2, 0]]]
            ascertainment: ['hcneaden']
            rec_obs : ['Physical_Pos']
        CN4archaicadmixture:
            coverage : [[[0.03, 0]], [[0.1, 0]], [[0.5, 0]], [[2, 0]]]
            ascertainment: ['archaicadmixture']
            rec_obs : ['Physical_Pos']
        C4hcneaden:
            coverage : 
                - [ [0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0]]
                - [ [0.2, 0.000],[0.2, 0.010],[0.2, 0.020],[0.2, 0.030],[0.2, 0.040],[0.2, 0.050],[0.2, 0.060],[0.2, 0.070],[0.2, 0.080],[0.2, 0.090]] #Dir(1)
                - [ [0.2, 0.000],[0.2, 0.020],[0.2, 0.040],[0.2, 0.120],[0.2, 0.160],[0.2, 0.200],[0.2, 0.240],[0.2, 0.280],[0.2, 0.320],[0.2, 0.360]] #Dir(1)
                - [ [0.2, 0.000],[0.2, 0.050],[0.2, 0.100],[0.2, 0.150],[0.2, 0.200],[0.2, 0.250],[0.2, 0.300],[0.2, 0.350],[0.2, 0.400],[0.2, 0.450]] #Dir(1)
                - [ [0.2, 0.000],[0.2, 0.100],[0.2, 0.200],[0.2, 0.300],[0.2, 0.400],[0.2, 0.500],[0.2, 0.600],[0.2, 0.700],[0.2, 0.800],[0.2, 0.900]] #Dir(1)
            ascertainment: ['hcneaden']
            rec_obs : ['Physical_Pos']
        C4archaics:
            coverage : 
                - [ [0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0]]
                - [ [0.2, 0.000],[0.2, 0.010],[0.2, 0.020],[0.2, 0.030],[0.2, 0.040],[0.2, 0.050],[0.2, 0.060],[0.2, 0.070],[0.2, 0.080],[0.2, 0.090]] #Dir(1)
                - [ [0.2, 0.000],[0.2, 0.020],[0.2, 0.040],[0.2, 0.120],[0.2, 0.160],[0.2, 0.200],[0.2, 0.240],[0.2, 0.280],[0.2, 0.320],[0.2, 0.360]] #Dir(1)
                - [ [0.2, 0.000],[0.2, 0.050],[0.2, 0.100],[0.2, 0.150],[0.2, 0.200],[0.2, 0.250],[0.2, 0.300],[0.2, 0.350],[0.2, 0.400],[0.2, 0.450]] #Dir(1)
                - [ [0.2, 0.000],[0.2, 0.100],[0.2, 0.200],[0.2, 0.300],[0.2, 0.400],[0.2, 0.500],[0.2, 0.600],[0.2, 0.700],[0.2, 0.800],[0.2, 0.900]] #Dir(1)
            ascertainment: ['archaics']
            rec_obs : ['Physical_Pos']
        C4archaicadmixture:
            coverage : 
                - [ [0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0],[0.2, 0]]
                - [ [0.2, 0.000],[0.2, 0.010],[0.2, 0.020],[0.2, 0.030],[0.2, 0.040],[0.2, 0.050],[0.2, 0.060],[0.2, 0.070],[0.2, 0.080],[0.2, 0.090]] #Dir(1)
                - [ [0.2, 0.000],[0.2, 0.020],[0.2, 0.040],[0.2, 0.120],[0.2, 0.160],[0.2, 0.200],[0.2, 0.240],[0.2, 0.280],[0.2, 0.320],[0.2, 0.360]] #Dir(1)
                - [ [0.2, 0.000],[0.2, 0.050],[0.2, 0.100],[0.2, 0.150],[0.2, 0.200],[0.2, 0.250],[0.2, 0.300],[0.2, 0.350],[0.2, 0.400],[0.2, 0.450]] #Dir(1)
                - [ [0.2, 0.000],[0.2, 0.100],[0.2, 0.200],[0.2, 0.300],[0.2, 0.400],[0.2, 0.500],[0.2, 0.600],[0.2, 0.700],[0.2, 0.800],[0.2, 0.900]] #Dir(1)
            ascertainment: ['archaicadmixture']
            rec_obs : ['Physical_Pos']

set:
    frag_human1:
        admixfrog: A4binsMH
        sim: SBasic
        rle: RBasic
        demography: DHuman1
        coverage: C4nocont
